[package]
name = "sozu"
description = "sozu, a fast, reliable, hot reconfigurable HTTP reverse proxy"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozu"
homepage = "http://sozu.io"
version = "0.14.1"
license = "AGPL-3.0"
authors = [
  "Geoffroy Couprie <geo.couprie@gmail.com>",
  "Eloi Demolis <eloi.demolis@clever-cloud.com>",
  "Emmanuel Bosquet <emmanuel.bosquet@clever-cloud.com>",
  "Florentin Dubois <florentin.dubois@clever-cloud.com>"
]
categories = ["network-programming"]
edition="2021"
include = [
  "README.md",
  "Cargo.toml",
  "src/**/*",
]

[[bin]]
name = "sozu"

[dependencies]
anyhow = "^1.0.65"
async-dup = "^1.2.2"
async-io = "^1.9.0"
clap = { version = "^4.0.14", features = ["derive"] }
futures = "^0.3.24"
futures-lite = "^1.12.0"
hex = "^0.4.3"
jemallocator = { version = "^0.5.0", optional = true }
lazy_static = "^1.4.0"
libc = "^0.2.135"
log = "^0.4.17"
mio = { version = "^0.8.4", features = [ "os-poll", "net" ] }
nix  = "^0.25.0"
nom = "^7.1.1"
paw = "^1.0.0"
prettytable-rs = { version = "^0.9.0", default-features = false }
serde = { version = "^1.0.145", features = ["derive"] }
serde_json = "^1.0.86"
time = "^0.3.15"
rand = "^0.8.5"
regex = "^1.6.0"
slab = "^0.4.7"
smol = "^1.2.5"
tempfile = "^3.3.0"
termion = "^1.5.6"

sozu-command-lib = { path = "../command" }
sozu-lib = { path = "../lib"} 

[target.'cfg(target_os="linux")'.dependencies]
num_cpus = "^1.13.1"

[features]
default = [ "jemallocator" ]
unstable = []
logs-debug = ["sozu-lib/logs-debug", "sozu-command-lib/logs-debug"]
logs-trace = ["sozu-lib/logs-trace", "sozu-command-lib/logs-trace"]
use-openssl = ["sozu-lib/use-openssl"]
tolerant-http1-parser = ["sozu-lib/tolerant-http1-parser"]

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }
